language: rust

rust:
    - stable

cache: cargo

before_script: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  rustup component add clippy-preview

script:
- cargo build
- cargo clippy
- cargo test

after_success: |
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
